### ISSUE TITLE
Does action recognition not require the start time and end time?

### ISSUE THREAD

**Issue by JihwanEom** [OpenGVLab/efficient-video-recognition#5]
Hi, I have a question as a beginner for action recognition task.

My question is same with title, does action recognition not use start time(frame) and end time information?

I confirmed kinetics400 dataset has time information that contains when the action starts and ends.

If there is many action in one video file, I think this time information is needed, but in this repo, I understand EVL only requires the label of video, not include time information.

Could you tell me about this?

Thank you!

**Comment by linziyi96** [comment]
We expect the files in the data list to be already trimmed according to the
start and end time, i.e. each file should only contain around 10 seconds of
video instead of the full video of a YouTube id.

We currently do not support online trimming. Videos are usually trimmed in
the download code (e.g.
https://github.com/activitynet/ActivityNet/tree/master/Crawler/Kinetics)
since otherwise they may take up too much space.

Best,
Ziyi

**Comment by JihwanEom** [comment]
Thank you for quick reply!
Do you mean EVL does not use full video as data input, uses trimmed video (around 10 seconds)?

Then, can I suppose below annotation format for EVL?
```
<path_n> <label_n>
3B32lodo2M_1 0
3B32lodo2M_2 1  # if 3B32lodo2M has two actions, split and re-match the labels!
bwYZwnwb8E 4
...
```

Last question, can I get trimmed video if I download kinetics from the link that you mentioned?

Best regards,
Jihwan

**Comment by linziyi96** [comment]
Yes to all questions.

Best,
Ziyi

**Comment by JihwanEom** [comment]
Thank you and thank you 😄 I think I can close this issue. Have a good weekend!
